version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - DOTNET_URLS=http://+:80
    networks:
      - app-network

  frontend:
    build:
      context: ./client
    ports:
      - "8081:80"
    environment:
      - REACT_APP_API_BASE_URL=http://backend:80  # Используем имя сервиса backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
